name: Publish container
on:
  push:
    branches:
    - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout master
      uses: actions/checkout@master
      id: checkout
    - name: Logging in to container registry...
      env:
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Building Docker image...
      env:
        DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      run:
        docker build --rm -t $DOCKER_IMAGE:latest -t $DOCKER_IMAGE:master-$(echo ${GITHUB_SHA} | head -c7) .
    - name: Publishing image...
      env:
        DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      run: docker push $DOCKER_IMAGE:master-$(echo ${GITHUB_SHA} | head -c7)
    - name: Tag this with latest...
      env:
        DOCKER_IMAGE: ${{ secrets.DOCKER_IMAGE }}
      run: docker push $DOCKER_IMAGE:latest
